export const FarmerDetailsList = [
  {
    id: "1",
    key: "பெயர்",
    name: "name",
  },
  {
    id: "2",
    key: "தந்தை பெயர் ",
    name: "fatherName",
  },
  {
    id: "3",
    key: "கணவர் / மனைவி பெயர் ",
    name: "husbandName",
  },
  {
    id: "4",
    key: "பிறந்த தேதி ",
    name: "DOB",
  },
  {
    id: "5",
    key: "கைபேசி எண் ",
    name: "phoneNumber",
  },
  {
    id: "6",
    key: "ஆதார் எண் ",
    name: "aadharNumber",
  },
  {
    id: "7",
    key: "வாக்காளர் அட்டை எண்  ",
    name: "voterIdNumber",
  },
  {
    id: "8",
    key: "சர்வே எண் ",
    name: "surveyNo",
  },
  {
    id: "9",
    key: "ஏக்கர் ",
    name: "acre",
  },
  {
    id: "10",
    key: "பாலினம் ",
    name: "gender",
  },
  {
    id: "11",
    key: "கல்வி ",
    name: "education",
  },
  {
    id: "12",
    key: "முகவரி ",
    name: "address",
  },
  {
    id: "13",
    key: "ஊர் ",
    name: "village",
  },
  {
    id: "14",
    key: "வட்டம் ",
    name: "circle",
  },
  {
    id: "15",
    key: "மாவட்டம் ",
    name: "district",
  },
  {
    id: "16",
    key: "பின் கோடு ",
    name: "pincode",
  },
];

export const FARMER_DATA = [
  {
    gender: "male",
    landType: "DRYLAND",
    irrigationType: null,
    farmerType: "SMALL",
    isAdmin: false,
    isGroupAdmin: false,
    _id: "610bcc09cdb7137b771ab755",
    name: "ANTHONIRAJ",
    phoneNumber: "9865693404",
    fatherName: "MATHURANAYAGAM",
    husbandName: "",
    farmerGroup: "அறுபதாம் சம்பா",
    aadharNumber: "8023 2245 2735",
    DOB: "1984-07-11",
    address: "TEACHERS NAGAR,VIRIYUR",
    acre: 100,
    surveyNo: "57/1A",
    "IRRIGATION TYPE": "RAINFED",
    cropType: "RAGI",
    cattle: "1",
    published_at: "2021-08-05T11:30:12.068Z",
    circle: null,
    district: null,
    education: null,
    pincode: null,
    updatedAt: "2022-09-02T06:36:13.221Z",
    village: null,
    voterIdNumber: null,
    membershipId: "347",
    id: "610bcc09cdb7137b771ab755",
  },
];
